221011 Django 13일차/pjt_1004/accounts/urls.py
from django.urls import path
from . import views

# app name 쓰는 이유?
# 우리는 기본적으로 URL을 모두 변수화해서 쓰고 있음
# Template, View에서 직접 '/accounts/' X
# app_name과 path 이름으로

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('<int:pk>/', views.detail, name='detail'),
]

221011 Django 13일차/pjt_1004/pjt_1004/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("practice/", include("practice.urls")),
    path('accounts/', include('accounts.urls')),
]

221011 Django 13일차/pjt_1004/practice/urls.py
# URL 설정을 app 단위로!

from django.urls import path
from . import views

app_name = "practice"

urlpatterns = [
    path("", views.index, name="index"),
    # path("new/", views.new, name="new"),
    path("create/", views.create, name="create"),
    path("<int:pk>/", views.detail, name="detail"),
    path("<int:pk>/update", views.update, name="update"),
]

221011 Django 13일차/pjt_1004/practice/models.py
from django.db import models

# Create your models here.

"""
# 게시판 기능
# 제목 - 20글자 이내
# 내용 - 긴 글
# 글 작성시간, 수정시간(자동으로 기록, 날짜/시간)
"""

# 1. 모델 설계 (DB 스키마 설계)
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

221011 Django 13일차/pjt_1004/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username',)

221011 Django 13일차/pjt_1004/practice/forms.py
from django import forms
from .models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content"]

221011 Django 13일차/pjt_1004/accounts/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
# from .models import User
from django.contrib.auth import get_user_model

# Create your views here.
def signup(request):
    # POST 요청 처리
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('practice:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user' : user,
    }

    return render(request, 'accounts/detail.html', context)

221011 Django 13일차/pjt_1004/practice/views.py
from django.shortcuts import render, redirect
from practice.models import Article
from .forms import ArticleForm

# Create your views here.
def index(request):
    article = Article.objects.order_by("-pk")
    context = {
        "article": article,
    }
    return render(request, "practice/index.html", context)


# def new(request):
#     article_form = ArticleForm()
#     context = {
#         "article_form": article_form,
#     }
#     return render(request, "practice/new.html", context=context)


def create(request):
    # title = request.POST.get("title")
    # content = request.POST.get("content")
    # Article.objects.create(title=title, content=content)
    # return redirect("practice:index")

    if request.method == "POST":
        # DB에 저장하는 로직
        article_form = ArticleForm(request.POST)
        # 유효성 검사
        if article_form.is_valid():
            # 유효하면 세이브
            article_form.save()
            return redirect("practice:index")
    else:
        article_form = ArticleForm()

    context = {
        "article_form": article_form,
    }
    return render(request, "practice/new.html", context=context)


def detail(request, pk):
    # 특정 글을 가져온다.
    article = Article.objects.get(pk=pk)
    context = {
        "article": article,
    }
    return render(request, "practice/detail.html", context)


def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == "POST":
        # POST : input 값 가져와서 검증하고, DB에 저장
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            # 유효성 검사 통과하면 상세보기 페이지로
            article_form.save()
            return redirect("practice:detail", article.pk)
        # 유효성검사 통과하지 않으면 => context부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        article_form = ArticleForm(instance=article)
    context = {
        "article_form": article_form,
    }
    return render(request, "practice/update.html", context)

221011 Django 13일차/pjt_1004/accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block body %}
  <h1>{{ user.username }}님의 프로필</h1>

{% endblock body %}

221011 Django 13일차/pjt_1004/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>회원가입</h1>
  {{ form.as_p}}
  <form action="" method='POST'>
    {% csrf_token %}
    {% comment %} {% bootstrap_form form %} {% endcomment %}
    {% bootstrap_button button_type='submit' content='OK' %}
    {% comment %} <a href="{% url 'practice:update' article.pk %}">수정하기</a> {% endcomment %}
  </form>

{% endblock body %}

221011 Django 13일차/pjt_1004/practice/templates/practice/detail.html
{% extends 'base.html' %}

{% block body %}
  <h1>{{ article.pk }}번 게시물</h1>
  <h2>{{ article.created_at }}
    |
    {{ article.updated_at }}</h2>
  <p>{{ article.content }}</p>

  <a href="{% url 'practice:update' article.pk %}">수정하기</a>
{% endblock %}

221011 Django 13일차/pjt_1004/practice/templates/practice/index.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
{% endblock %}

{% block body %}
  <h1>게시판</h1>
  <img src="{% static 'images/d600400.png' %}" alt="">
  <hr>
  {% for a in article %}
    <h3>
      <a href="{% url 'practice:detail' a.pk %}">{{ a.title }}</a>
    </h3>
    <h5>{{ a.created_at }}
      |
      {{ a.updated_at }}</h5>
    <hr>
  {% endfor %}
  <a href="{% url 'practice:create' %}">새 글 쓰기</a>
  {% comment %} <button class='btn btn-primary'>이게 되나?</button> {% endcomment %}
{% endblock %}

221011 Django 13일차/pjt_1004/practice/templates/practice/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>글쓰기</h1>
  <!-- form : 사용자에게 양식을 제공하고 값을 받아서(input : name, value), 서버에 전송(form : action, method) -->
  <form action="{% url 'practice:create' %}" method="POST">
    {% csrf_token %}

    {% comment %} {% for field in article_form %}
      <p>{{ field }}</p>
      <p>{{ field.label_tag }}</p>
    {% endfor %} {% endcomment %}

    {% bootstrap_form article_form %}
    {# article_form.as_p #}
    {% bootstrap_button button_type="submit" content="글쓰기" %}
    {% comment %} <!-- <label for="title">제목 : </label> <input type="text" name="title" id="title"> <label for="content">내용 : </label> <textarea name="content" id="content" cols="30" rows="10"></textarea> -->
    <!-- <input type="submit" value="글쓰기"> --> {% endcomment %}
    
  </form>
{% endblock %}

221011 Django 13일차/pjt_1004/practice/templates/practice/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>수정하기</h1>

  <form action="" method="POST">
    {% csrf_token %}
    {% comment %} {{ article_form.as_p }} {% endcomment %}
    {% comment %} <input type="submit" value="수정"> {% endcomment %}
    {% bootstrap_form article_form %}
    {% bootstrap_button button_type='submit' content='수정하기' %}
  </form>
{% endblock %}