221013 Django 15일차/Django-project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # 회원 목록 조회
    path('', views.index, name='index'),
    # 회원 세부 정보 조회
    path('<int:pk>/', views.detail, name='detail'),
    # 회원가입
    path('signup/', views.signup, name='signup'),
    # 로그인
    path('login/', views.login, name='login'),
    # 로그아웃
    path('logout/', views.logout, name='logout'),
    # 회원 정보 수정
    path('update/', views.update, name='update'),
    # 비밀번호 변경
    path('password/', views.change_password, name='change_password'),
]

221013 Django 15일차/Django-project/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    # 글 목록 조회
    path('', views.index, name='index'),
    # 글 세부
    path('detail/<int:pk>', views.detail, name='detail'),

    # 새 글 쓰기 창 띄우기 (모델폼 쓰지 않는 CRUD) - 필요하면 movie-community 예린님 페어프로젝트 파일 확인하기
    # path('new/', views.new, name='new'),
    # 새로운 글 생성
    path('create/', views.create, name='create'),

    # 글 수정하기 창 (모델폼 쓰지 않는 CRUD)
    # path('edit/<int:pk>', views.edit, name='edit'),
    # 글 수정 기능
    path('update/<int:pk>', views.update, name='update'),

    # 글 삭제 기능
    path('delete/<int:pk>', views.delete, name='delete'),
]

221013 Django 15일차/Django-project/pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

221013 Django 15일차/Django-project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    # pass
    @property
    def full_name(self):
        return f'{self.last_name}{self.first_name}'

221013 Django 15일차/Django-project/articles/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

221013 Django 15일차/Django-project/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from .models import User
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

221013 Django 15일차/Django-project/articles/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('title', 'content')

221013 Django 15일차/Django-project/accounts/views.py
from multiprocessing import context
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash


# Create your views here.

# 회원 목록 조회
@login_required
def index(request):
    users = get_user_model().objects.order_by('pk')
    context = {
        'users' : users,
    }
    return render(request, 'accounts/index.html', context)

# 회원 세부 정보 조회
@login_required
def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user' : user,
    }
    return render(request, 'accounts/detail.html', context)

# 회원 가입 폼
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            # 바로 로그인 시켜주는 경우
            # user = form.save()  # ModelForm의 save 메서드의 리턴값은 해당 모델의 인스턴스다!
            # auth_login(request, user)  # 로그인
        
            # 로그인 시켜주지 않고 로그인 창으로 보내는 경우
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

# 로그인
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            # local~/accounts/login/?next=/articles/1/update/
            # request.GET.get('next') : /articles/1/update/

            # if request.GET.get('next'):
            #     return redirect(request.GET.get('next'))
            # else:
            #     return redirect('accounts:index')
            return redirect(request.GET.get('next') or 'main')
    else:
        form = AuthenticationForm()

    context = {
        'form' : form
    }
    return render(request, 'accounts/login.html', context)

# 로그아웃
def logout(request):
    auth_logout(request)
    return redirect('main')

# 회원 정보 수정
@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            # return redirect('accounts:detail', request.user.pk)
            return redirect('accounts:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/update.html', context)

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        # form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('accounts:detail', request.user.pk)
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

221013 Django 15일차/Django-project/articles/views.py
from django.shortcuts import render, redirect
from articles.forms import ReviewForm
from .models import Review
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    reviews = Review.objects.all()
    context = {
        'reviews' : reviews,
    }
    return render(request, 'articles/index.html', context)

def detail(request, pk):
    review = Review.objects.get(pk=pk)
    context = {
        'review' : review,
    }
    return render(request, 'articles/detail.html', context)

@login_required
def create(request):
    # if request.user.is_authenticated:
    # 유효성 검사
    if request.method == 'POST':
        # DB에 저장하는 로직
        review_form = ReviewForm(request.POST)
        if review_form.is_valid():
            review_form.save()
            return redirect('articles:index')
    else:
        review_form = ReviewForm()
    
    context = {
        'review_form' : review_form,
    }
    return render(request, 'articles/new.html', context=context)    
    # else:
    #     # 여러가지 방법이 있음
    #     # return render(....)
    #     return redirect('accounts:login')


@login_required
def update(request, pk):
    review = Review.objects.get(pk=pk)
    if request.method == "POST":
        # POST : input 값 가져와서 검증하고, DB에 저장
        review_form = ReviewForm(request.POST, instance=review)
        # 유효성 검사
        if review_form.is_valid():
            # 유효하면 세이브
            review_form.save()
            # 유효성 검사 통과하면 상세보기 페이지로
            return redirect("articles:detail", review.pk)
            
    # 유효성검사 통과하지 않으면 => context부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        review_form = ReviewForm(instance=review)

    context = {
        "review_form": review_form,
    }
    return render(request, "articles/update.html", context)

@login_required
def delete(request, pk):
    Review.objects.get(pk=pk).delete()
    return redirect('articles:index')

221013 Django 15일차/Django-project/pjt/views.py
from django.shortcuts import render, redirect

def main(request):
    return render(request, 'main.html')

221013 Django 15일차/Django-project/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

  <h1>비밀번호 변경</h1>
  {% comment %}{% endcomment %}
  <form action="{% url 'accounts:change_password' %}" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='비밀번호 변경' %}
  </form> 

{% endblock body %}

221013 Django 15일차/Django-project/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

  <h1>{{ user.username }}
    님의 프로필</h1>
  <h2>{{ user.full_name }}</h2>
  <h2>{{ user.email }}</h2>

  <br>
  <br>
  가입한 날짜 :
  {{ user.date_joined }}
  <br>
  마지막 로그인 :
  {{ user.last_login }}

  <br>
  <br>
  <a class='btn btn-outline-warning' href="{% url 'accounts:index' %}">메인으로</a>
  <a class='btn btn-outline-info' href="{% url 'accounts:update' %}">수정하기</a>

{% endblock body %}

221013 Django 15일차/Django-project/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

  {% comment %} 회원 목록 테이블 {% endcomment %}

  {% comment %} 사용자 인증이 되었다면 (user도 되고 request.user도 됨) {% endcomment %}
  {% if request.user.is_authenticated %}
    <div class='d-flex align-items-center'>
      <h1>{{ request.user }}</h1>
      <a class='btn btn-outline-danger mx-4' href="{% url 'accounts:logout' %}" style='width: 90px; height:35px;'>로그아웃</a>
    </div>
  {% endif %}

  index.html

  <table class="table">
    <thead>
      <tr>
        <th scope="col">pk</th>
        <th scope="col">제목</th>
        <th scope="col">email</th>
      </tr>
    </thead>
    <tbody>
      {% for user in users %}
        <tr>
          <th>{{ user.pk }}</th>
          <td><a href="{% url 'accounts:detail' user.pk %}">{{ user.username }}</a></td>
          <td>{{ user.email }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock body %}

221013 Django 15일차/Django-project/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

  login.html

  <h1>로그인</h1>
  {% comment %}{% endcomment %}
  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='login' %}
  </form> 

{% endblock body %}

221013 Django 15일차/Django-project/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

  <h1>회원가입</h1>

  <br>

  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='OK' %}
    {% comment %}{% endcomment %}
    <a class='btn btn-outline-warning' href="{% url 'main' %}">go to main</a>
  </form>

{% endblock body %}

221013 Django 15일차/Django-project/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}

  login.html

  <h1>프로필 업데이트</h1>
  {% comment %}{% endcomment %}
  <form action="" method='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type='submit' content='수정' %}
  </form> 

{% endblock body %} 