221012 Django 14일차/login_pjt/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # 회원 목록 조회
    path('', views.index, name='index'),
    # 회원가입
    path('signup/', views.signup, name='signup'),
    # 회원 세부정보 조회
    path('<int:pk>/', views.detail, name='detail'), 
    # 로그인
    path('login/', views.login, name='login'),
    # 로그아웃
    path('logout/', views.logout, name='logout'),
]

221012 Django 14일차/login_pjt/login_pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('accounts/', include('accounts.urls')),
]

221012 Django 14일차/login_pjt/accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.
def index(request):
    users = get_user_model().objects.order_by('pk')
    context = {
        'users' : users,
    }
    return render(request, 'accounts/index.html', context)

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        # 유효성 검사
        if form.is_valid():
            form.save()
            # 앱의 index - 회원목록
            # return redirect('accounts:index')
            # 아주 메인 - 버튼들 있는 것
            return render(request, 'index.html')
    else:
        form = CustomUserCreationForm()

    context = {
        'form' : form,
    }
    return render(request, 'accounts/signup.html', context)

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user' : user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('accounts:index')
    else:
        form = AuthenticationForm()

    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('index')

221012 Django 14일차/login_pjt/login_pjt/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

221012 Django 14일차/login_pjt/login_pjt/templates/base.html
{% load django_bootstrap5 %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% bootstrap_css%}
    {% block css %}{% endblock css%}
  </head>

  <body>
    <div class="container my-5">
      <br>
      <br>
      {% block body %}{% endblock body %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>

221012 Django 14일차/login_pjt/login_pjt/templates/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% comment %} 
- 회원가입 페이지 이동 버튼
- 회원 목록 페이지 이동 버튼
- 로그인 상태에 따라 다른 화면 출력
  - 로그인 상태
    - 로그인 한 사용자의 username 출력
      - username 클릭 시 해당 회원 조회 페이지(프로필 페이지)로 이동
    - 로그아웃 버튼
  - 비 로그인 상태
    - 로그인 페이지 이동 버튼
    - 회원가입 페이지 이동 버튼 

{% endcomment %}

{% block body %}
  <h1>메인화면입니당</h1>

  <div class='d-flex flex-column'>

    {% comment %} 사용자가 로그인 상태일때 {% endcomment %}
    {% if request.user.is_authenticated %}
      <a href=""><h1>{{ request.user }}</h1></a>
      <a href="{% url 'accounts:logout' %}">
        <button class='btn btn-outline-danger my-1 w-100' type='submit'>로그아웃</button>
      </a>
      <a href="{% url 'accounts:index' %}"
        <button class='btn btn-primary my-1 w-100' type='submit'>회원 목록</button>
        {% comment %} {% bootstrap_button button_type = 'submit' content = '회원목록' %} {% endcomment %}
      </a>
    
    {% comment %} 사용자가 비로그인 상태일때 {% endcomment %}
    {% else %}
      <a href="{% url 'accounts:login' %}">
        <button class='btn btn-outline-primary my-1 w-100' type='submit'>로그인</button>
      </a>
      <a href="{% url 'accounts:signup' %}">  
        <button class='btn btn-outline-primary my-1 w-100' type='submit'>회원 가입</button>
        {% comment %} {% bootstrap_button button_type = 'submit' content = '회원가입' %} {% endcomment %}
      </a>
    {% endif %}

  </div>
{% endblock body %}