221006 Django 11일차/jango09_pjt/jango09_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("movies/", include("movies.urls")),
]

221006 Django 11일차/jango09_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    # 영화 데이터 목록 조회
    path("", views.index, name="index"),
    # 영화 데이터 정보 조회
    path("<int:pk>/", views.detail, name="detail"),
    # 영화 데이터 생성
    path("create/", views.create, name="create"),
    # 영화 데이터 수정
    path("<int:pk>/update/", views.update, name="update"),
    # 영화 데이터 삭제
    path("<int:pk>/delete/", views.delete, name="delete"),
]

221006 Django 11일차/jango09_pjt/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=150)
    summary = models.TextField(default='')
    running_time = models.IntegerField(default=0)

221006 Django 11일차/jango09_pjt/movies/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    
    class Meta:
        model = Movie
        fields = ('title', 'summary', 'running_time')

221006 Django 11일차/jango09_pjt/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movies = Movie.objects.order_by('pk')
    context = {
        'movies' : movies,
    }
    return render(request, 'movies/index.html', context)


def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie' : movie,
    }
    return render(request, 'movies/detail.html', context)


def create(request):
    # 유효성 검사
    if request.method == "POST":
        # DB에 저장하는 로직
        movie_form = MovieForm(request.POST)
        # 유효성 검사
        if movie_form.is_valid():
            # 유효하면 세이브
            movie_form.save()
            return redirect("movies:index")
    else:
        movie_form = MovieForm()

    context = {
        "movie_form": movie_form,
    }
    return render(request, "movies/new.html", context=context)


def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.method == "POST":
        # POST : input 값 가져와서 검증하고, DB에 저장
        movie_form = MovieForm(request.POST, instance=movie)
        # 유효성 검사
        if movie_form.is_valid():
            # 유효하면 세이브
            movie_form.save()
            # 유효성 검사 통과하면 상세보기 페이지로
            return redirect("movies:detail", movie.pk)

    # 유효성검사 통과하지 않으면 => context부터해서 오류메시지 담긴 article_form을 랜더링
    else:
        # GET : Form을 제공
        movie_form = MovieForm(instance=movie)

    context = {
        "movie_form": movie_form,
    }
    return render(request, "movies/update.html", context)


def delete(request, pk):
    Movie.objects.get(pk=pk).delete()
    return redirect('movies:index')

221006 Django 11일차/jango09_pjt/jango09_pjt/templates/base.html
{% load django_bootstrap5 %}
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Movie</title>
    {% bootstrap_css %}
    {% block css %}{% endblock css%}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid mx-3">
        <div>
          <img class='mx-1' src="{% static 'images/movie-icon.png' %}" alt="">
          <a class="navbar-brand" href="">Movie</a>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:index' %}">목록</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'movies:create' %}">추가</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class='container my-3'>
      {% block body %}{% endblock body %}
    </div>
    {% bootstrap_javascript %}
  </body>

</html>

221006 Django 11일차/jango09_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>detail.html</h1>
  <p>글 제목 누르면 글의 내용과 수정 삭제 버튼</p>


    <div class='d-flex justify-content-between' style='height: 120px'>
      <h1 class='my-3'>{{ movie.title }}</h1>
      <h4 class=''>{{ movie.running_time }}분</h4>
    </div>
    <p>{{ movie.summary }}</p>
    
  {% comment %} {% bootstrap_button button_type = 'submit' content = 'OK' %} {% endcomment %}
  <div class='d-flex justify-content-end'>
    <a class='btn btn-outline-success mx-1' href="{% url 'movies:update' movie.pk %}">수정</a>
    <a class='btn btn-outline-danger mx-1' href="{% url 'movies:delete' movie.pk %}">삭제</a>
  </div>
{% endblock %}

221006 Django 11일차/jango09_pjt/movies/templates/movies/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>index.html</h1>
  <p>목록을 출력해서 게시판처럼 보여주기</p>
  {% comment %} <form action="" method="POST">
    {% csrf_token %}

    {% bootstrap_form article_form %}
    {% bootstrap_button button_type='submit' content='수정하기' %}
  </form> {% endcomment %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col">pk</th>
        <th scope="col">영화 제목</th>
      </tr>
    </thead>
    <tbody>
      {% for movie in movies %}
        <tr>
          <th scope="row">{{ movie.pk }}</th>
          <td><a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

221006 Django 11일차/jango09_pjt/movies/templates/movies/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>new.html</h1>
  <p>새 글 쓰기</p>
  <form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}

    {% bootstrap_form movie_form %}
    {% comment %} {% bootstrap_button button_type = 'submit' content = 'OK' %} {% endcomment %}
    <button class='btn btn-primary' type='submit'>OK</button>
  </form>
{% endblock %}

221006 Django 11일차/jango09_pjt/movies/templates/movies/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
  <h1>update.html</h1>
  <p>수정하기</p>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form movie_form %}
    {% comment %} {% bootstrap_button button_type = 'submit' content = 'OK' %} {% endcomment %}
    <button class='btn btn-success' type='submit'>수정</button>
  </form>
{% endblock %}